server:
  port: 8080

spring:
  application:
    name: capitascore
  datasource:
    url: jdbc:mysql://localhost:3306/capitascore?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

riot:
  api-key: RGAPI-3ec55b1f-cb1c-45d5-9ccf-ca21502c926e
  region: br1
  americas-base-url: https://americas.api.riotgames.com
  match-base-path: /lol/match/v5
